server:
  port: 8080
  servlet:
    context-path: /dictionary
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/dictionary"
    username: root
    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true